# Generated by Django 5.1.3 on 2025-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
