# Generated by Django 5.1.3 on 2025-03-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_enrollment_units'),
        ('submissions', '0002_studentsubmission_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
