# Generated by Django 5.1.3 on 2025-03-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_assignment_unit_alter_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
    ]
