# Generated by Django 5.1.3 on 2025-03-26 06:36

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_assignment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='student_attachment',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.assignment_upload_path_student),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.assignment_upload_path),
        ),
    ]
