# Generated by Django 5.1.3 on 2025-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_studentsubmission_student_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
