# Generated by Django 5.1.3 on 2024-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='sent',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
