# Generated by Django 5.1.3 on 2024-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remove_reminder_sent_reminder_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_sent',
            new_name='sent',
        ),
        migrations.AddField(
            model_name='assignment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
