# Generated by Django 5.1.3 on 2025-01-24 07:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='reminder_sent',
            new_name='submitted',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='procrastination_level',
        ),
        migrations.AddField(
            model_name='reminder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 24, 7, 14, 56, 37126, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_due', models.IntegerField()),
                ('reminders_sent', models.IntegerField()),
                ('submitted_on_time', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.student')),
            ],
        ),
    ]
