# Generated by Django 5.1.3 on 2025-01-24 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_rename_reminder_sent_assignment_submitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='submitted',
            new_name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 8, 10, 10, 43450, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='procrastination_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='SubmissionHistory',
        ),
    ]
