# Generated by Django 5.1.3 on 2025-01-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_rename_submitted_assignment_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
