# Generated by Django 5.1.3 on 2025-02-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='submission_history',
            field=models.JSONField(default=list),
        ),
    ]
