# Generated by Django 5.1.3 on 2025-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_enrollment_course_students_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], default='Year 1', max_length=10),
        ),
    ]
