# Generated by Django 5.1.3 on 2025-03-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='available_for_years',
            field=models.ManyToManyField(blank=True, related_name='available_units', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
    ]
