# Generated by Django 5.1.3 on 2025-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_unit_available_for_years_alter_studentprofile_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.AlterField(
            model_name='unit',
            name='available_for_years',
            field=models.ManyToManyField(blank=True, related_name='available_units', to='students.yearcategory'),
        ),
    ]
