# Generated by Django 5.1.3 on 2025-03-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_yearcategory_remove_studentprofile_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='students.yearcategory'),
            preserve_default=False,
        ),
    ]
