# Generated by Django 5.1.3 on 2025-03-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_year_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='units',
            field=models.ManyToManyField(blank=True, to='students.unit'),
        ),
    ]
